title: Research Methods & Professional Practice E-Portfolio
description: MSc Computer Science — University of Essex Online
url: https://yy23505.github.io
baseurl: /essex-rmpp-eportfolio
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

markdown: kramdown
permalink: /:categories/:title/
timezone: Europe/London
paginate: 5
locale: en-GB

search: true
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

collections:
  units:
    output: true
    permalink: /units/:name/

defaults:
  - scope: { path: "", type: "units" }
    values:
      layout: single
      classes: wide
      author_profile: false
      toc: true
      toc_sticky: true
      read_time: false
      sidebar:
        nav: "main"
  - scope: { path: "", type: "pages" }
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

author:
  name: Your Name
  avatar: /essex-rmpp-eportfolio/assets/avatar.jpg
  bio: MSc Computer Science (University of Essex Online)
  links:
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yy23505"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/<your-handle>"
